name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
      
jobs:
  version:
    name: Create new version 
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn
      
      - name: Unit test
        run: yarn test
      
      - name: E2E test
        run: yarn cypress:run

      - name: Generate new version
        run: npm version minor

      - name: Push new version tag to repository
        run: git push origin main --tags

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main
    
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Publish
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_POKELIST_FER }}'
          channelId: live
          projectId: pokelist-fer
